# wrangler.toml
name = "keep-awake"
main = "src/ping.js"
compatibility_date = "2025-11-24"

workers_dev = true
preview_urls = true

# KV Namespace (споделен с Status Worker)
[[kv_namespaces]]
binding = "UPTIME_LOG"
id = "46095dfcaa87492ea5562d0741ad2f4a"

# Cron trigger на всеки 10 минути от 04:00 до 22:59 UTC → покрива 06:00–01:00 BG (зима/лято)
[triggers]
crons = ["*/10 4-22 * * *"]